version: "3"
services:
  flask-api-demo:
    image: flask-api-demo:v1.0.0
    container_name: flask-api-demo
    restart: always
    privileged: true

    environment:
      - PROCESSES=4
      - HTTP_TIMEOUT=60

    ports:
      - "2021:5000"

    volumes:
      - "/data/flask-api-demo/data:/data/data"
      - "/data/flask-api-demo/log:/data/log"
      - "./:/work"

  flask-postgres:
    image: postgres:12.6
    container_name: flask-postgres
    restart: always
    privileged: true

    ports:
      - "20211:5432"

    environment:
      # 使用上海时区
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=flask

    volumes:
      - /data/flask-api-demo/data/postgres:/var/lib/postgresql/data

  flask-redis:
    image: redis:6
    container_name: flask-redis
    restart: always
    privileged: true

    ports:
      - "20212:6379"

    volumes:
      - /data/flask-api-demo/data/redis:/data

networks:
  default:
    external:
      name: flask