version: 2
services:
  flask-api:
    image: flask-api:v1
    container_name: flask-api
    restart: always
    privileged: true

    environment:
      - PROCESSES=4

    volumes:
      - "./log:/data/log/"